import { dirname, join } from "node:path";
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync } from "node:fs";
import { isAbsolute, relative, resolve, sep } from "node:path";

import { BaseCheckpointSaver } from "@langchain/langgraph";
import { SqliteSaver } from "@langchain/langgraph-checkpoint-sqlite";
import Database from "better-sqlite3";

import { WorkflowArtifactStore } from "./artifacts.ts";
import { migrateWorkflowDatabase } from "./migrations.ts";
import { WorkflowProjectionService } from "./projection.ts";
import { type WorkflowArtifactKind, type WorkflowArtifactRecord, WorkflowRepository } from "./repository.ts";

export interface OpenWorkflowDatabaseOptions {
  readonly artifactRoot?: string;
}

export interface OpenWorkflowDatabase {
  readonly checkpointer: BaseCheckpointSaver;
  readonly repository: WorkflowRepository;
  readonly artifacts: WorkflowArtifactStore;
  readonly projections: WorkflowProjectionService;
  close(): void;
}

/** LangGraph-compatible checkpoint facade that keeps the SQLite saver unreachable. */
class WorkflowCheckpointSaver extends BaseCheckpointSaver {
  readonly #inner: SqliteSaver;

  public constructor(inner: SqliteSaver) {
    super(inner.serde);
    this.#inner = inner;
  }

  override getTuple(...args: Parameters<BaseCheckpointSaver["getTuple"]>): ReturnType<BaseCheckpointSaver["getTuple"]> {
    return this.#inner.getTuple(...args);
  }

  override list(...args: Parameters<BaseCheckpointSaver["list"]>): ReturnType<BaseCheckpointSaver["list"]> {
    return this.#inner.list(...args);
  }

  override put(...args: Parameters<BaseCheckpointSaver["put"]>): ReturnType<BaseCheckpointSaver["put"]> {
    return this.#inner.put(args[0], args[1], args[2]);
  }

  override putWrites(...args: Parameters<BaseCheckpointSaver["putWrites"]>): ReturnType<BaseCheckpointSaver["putWrites"]> {
    return this.#inner.putWrites(...args);
  }

  override deleteThread(...args: Parameters<BaseCheckpointSaver["deleteThread"]>): ReturnType<BaseCheckpointSaver["deleteThread"]> {
    return this.#inner.deleteThread(...args);
  }

  override getDeltaChannelHistory(...args: Parameters<BaseCheckpointSaver["getDeltaChannelHistory"]>): ReturnType<BaseCheckpointSaver["getDeltaChannelHistory"]> {
    return this.#inner.getDeltaChannelHistory(...args);
  }

  override getNextVersion(current: number | undefined): number {
    return this.#inner.getNextVersion(current);
  }
}

/** Opens one connection shared by LangGraph checkpoints and product persistence. */
export function openWorkflowDatabase(path: string, options: OpenWorkflowDatabaseOptions = {}): OpenWorkflowDatabase {
  if (path !== ":memory:") mkdirSync(dirname(path), { recursive: true });
  const database = new Database(path);
  database.pragma("journal_mode = WAL");
  database.pragma("foreign_keys = ON");
  migrateWorkflowDatabase(database);
  const artifactRoot = options.artifactRoot ?? join(dirname(path), "workflow-artifacts");
  const repository = new WorkflowRepository(database, artifactRoot);
  const artifacts = new WorkflowArtifactStore(artifactRoot, repository, createArtifactCommitter(database, artifactRoot));
  const projections = new WorkflowProjectionService(repository);
  const checkpointer = new WorkflowCheckpointSaver(new SqliteSaver(database));
  return Object.freeze({ checkpointer, repository, artifacts, projections, close: () => database.close() });
}

function createArtifactCommitter(database: Database.Database, artifactRoot: string): (input: {
  artifactRef: string;
  runId: string;
  kind: WorkflowArtifactKind;
  relativePath: string;
  sha256: string;
  byteSize: number;
}) => WorkflowArtifactRecord {
  return (input) => {
    const expected = new RegExp(`^runs/${escapeRegex(input.runId)}/${escapeRegex(input.kind)}/[0-9a-f-]{36}\\.json$`);
    if (input.artifactRef !== input.relativePath || !expected.test(input.artifactRef)) throw new Error("Artifact path is not generated by WorkflowArtifactStore");
    if (!/^[a-f0-9]{64}$/.test(input.sha256) || !Number.isInteger(input.byteSize) || input.byteSize < 0) throw new Error("Invalid artifact integrity metadata");
    const bytes = readFileSync(resolveArtifactPath(artifactRoot, input.relativePath));
    if (bytes.byteLength !== input.byteSize || createHash("sha256").update(bytes).digest("hex") !== input.sha256) throw new Error("Artifact integrity metadata does not match durable artifact");
    return database.transaction(() => {
      const timestamp = new Date().toISOString();
      const result = database.prepare(`INSERT OR IGNORE INTO workflow_artifacts (artifact_ref, run_id, kind, relative_path, sha256, byte_size, status, created_at, updated_at)
        VALUES (?, ?, ?, ?, ?, ?, 'ready', ?, ?)`)
        .run(input.artifactRef, input.runId, input.kind, input.relativePath, input.sha256, input.byteSize, timestamp, timestamp);
      const record = database.prepare("SELECT artifact_ref, run_id, kind, relative_path, sha256, byte_size, status FROM workflow_artifacts WHERE artifact_ref = ?").get(input.artifactRef) as {
        artifact_ref: string; run_id: string; kind: WorkflowArtifactKind; relative_path: string; sha256: string; byte_size: number; status: WorkflowArtifactRecord["status"];
      } | undefined;
      if (!record) throw new Error("Failed to persist workflow artifact");
      if (record.run_id !== input.runId || record.relative_path !== input.relativePath || record.sha256 !== input.sha256 || record.byte_size !== input.byteSize) throw new Error("Artifact reference already has different metadata");
      if (result.changes === 1) database.prepare("INSERT INTO workflow_change_sequence (run_id, change_kind, created_at) VALUES (?, 'artifact-recorded', ?)").run(input.runId, timestamp);
      return { artifactRef: record.artifact_ref, runId: record.run_id, kind: record.kind, relativePath: record.relative_path, sha256: record.sha256, byteSize: record.byte_size, status: record.status };
    })();
  };
}

function resolveArtifactPath(rootPath: string, relativePath: string): string {
  if (!relativePath || isAbsolute(relativePath)) throw new Error("Invalid relative artifact path");
  const root = resolve(rootPath);
  const candidate = resolve(root, relativePath);
  const fromRoot = relative(root, candidate);
  if (fromRoot === "" || fromRoot === ".." || fromRoot.startsWith(`..${sep}`) || isAbsolute(fromRoot)) throw new Error("Invalid relative artifact path");
  return candidate;
}

function escapeRegex(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
